#pragma config(StandardModel, "RVW Buggybot")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int speedvalue = 40;
int turnSpeed = 15;
short facing = 0;  //direction robot is facing
short openPath = 30;
short son1 = 0;



void goBackward()
{
	facing = SensorValue(gyro);
	backward(0.05, rotations, speedvalue);
}



void checkTooClose()
{
	son1 = SensorValue(sonar);
	if (son1 < openPath)
	{
		goBackward();
	}
}


void goLeft()
{
	turnLeft(250, degrees, turnSpeed);
	son1 = SensorValue(sonar);
	checkTooClose();

}

void goRight()
{
	turnRight(25, degrees, turnSpeed);

}

void goForward()
{
	facing = SensorValue(gyro);
	forward(0.049, seconds, speedvalue);
}



void proceed()
{
	while (SensorValue(sonar) > (openPath-5))
	{
		goForward();
	}

}


bool lookRight()
{
	bool found = true;
	son1 = SensorValue(sonar);
	while ((son1 < openPath))
	{
		if (SensorValue(gyro) > (facing + 500))
		{
			found = false;
			break;
		}
		checkTooClose();
		goRight();
		wait1Msec(10);
		son1 = SensorValue(sonar);
	}
	return found;
}


void lookFarRight()
{
	//turnRight(159, degrees, turnSpeed);
	son1 = SensorValue(sonar);
	while ((son1 < openPath))
	{
  	goRight();
		wait1Msec(10);
		son1 = SensorValue(sonar);
	}
}


bool lookLeft()
{
	bool found = true;
	goLeft();
	wait1Msec(10);
	son1 = SensorValue(sonar);
	if (son1 < openPath)
	{
		found = false;
	}
	return found;
}


void lookAround()
{
	son1 = SensorValue(sonar);
	if (lookRight() != true)
	{
		if (lookLeft() != true)
		{
			lookFarRight();
		}
	}
}


void whichWay()
{
	lookAround();
}

task main()
{
	wait1Msec(50);
	while (true)
	{
		whichWay();
		proceed();
	}
}
