#pragma config(StandardModel, "RVW Buggybot")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#pragma config(Sensor, S3, lightSensor, sensorLightActive)

int speedvalue = 58;
float clearance = 1.25;

void goRight(float clearance)
{
		forward(clearance, rotations, speedvalue);
		turnRight(158.1, degrees, 15);

}


void goLeft(float clearance)
{
		forward(clearance, rotations, speedvalue);
		turnLeft(158.1, degrees, 15);

}

void goForward()
{
		//forward(0.125, rotations, 50);
		forward(0.049, seconds, speedvalue);

}



void findLine()
{
	  while (SensorValue(light) > 65)
		{
    		goForward();
		}
		stopAllMotors();
}

task main()
{
		wait1Msec(50);

		turnRight(158.1, degrees, 15);
    forward(3, rotations, speedvalue);
    findLine();

    goLeft(1.35);
    findLine();

    goLeft(1.20);
    findLine();

    goRight(1.06);
    findLine();
    //goSlightRight();


    forward(.5, rotations, speedvalue);
    findLine();
    //goSlightRight();
    forward(.5, rotations, speedvalue);
    findLine();



    goRight(clearance);
    findLine();

    goRight(clearance);
    findLine();



    goLeft(1.20);
    findLine();


    goLeft(clearance);
    findLine();

    forward(.3, rotations, speedvalue);

}
